imports:
    - php

filter:
    paths:
        - 'src/*'

tools:
    php_mess_detector: true
    php_analyzer: true
    php_cpd: true
    php_loc: true
    php_pdepend: true
    php_changetracking: true
